# data cleaning

## Import Libraries

In [1]:
import ast
import pandas as pd
import numpy as np

## Load Raw Data

In [2]:
df = pd.read_csv("../data/raw.csv", low_memory=False)
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [3]:
df.info()
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
count,45466,4494,45466,45466,7782,45466,45449,45455,45466,44512,...,45379,4.546000e+04,45203.000000,45460,45379,20412,45460,45460,45460.000000,45460.000000
unique,5,1698,1226,4069,7673,45436,45417,92,43373,44307,...,17336,NaN,NaN,1931,6,20283,42277,2,NaN,NaN
top,False,"{'id': 415931, 'name': 'The Bowery Boys', 'pos...",0,"[{'id': 18, 'name': 'Drama'}]",http://www.georgecarlin.com,141971,tt1180333,en,Hamlet,No overview found.,...,2008-01-01,NaN,NaN,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Based on a true story.,Cinderella,False,NaN,NaN
freq,45454,29,36573,5000,12,3,3,32269,8,133,...,136,NaN,NaN,22395,45014,7,11,45367,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1.120935e+07,94.128199,NaN,NaN,NaN,NaN,NaN,5.618207,109.897338
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,6.433225e+07,38.407810,NaN,NaN,NaN,NaN,NaN,1.924216,491.310374
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000e+00,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000e+00,85.000000,NaN,NaN,NaN,NaN,NaN,5.000000,3.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000e+00,95.000000,NaN,NaN,NaN,NaN,NaN,6.000000,10.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.000000e+00,107.000000,NaN,NaN,NaN,NaN,NaN,6.800000,34.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,2.787965e+09,1256.000000,NaN,NaN,NaN,NaN,NaN,10.000000,14075.000000

## Missing Values Analysis
Drop columns with high missing values or low relevance
Columns with more than 50% missing or those considered irrelevant for our analysis are removed.

In [4]:
cols_zero = ["budget", "revenue", "runtime"]

# to numeric & zero to NaN
for col in cols_zero:
    df[col] = pd.to_numeric(df[col], errors='coerce')
    df[col] = df[col].replace(0, np.nan)

# Percentage of missing data and sort
missing_precent = df.isnull().mean() * 100
missing_precent = missing_precent.sort_values(ascending=False)

# Columns with more then 50% missing data
high_missing_cols = missing_precent[missing_precent > 50].index.to_list()

# useless cols
useless_cols = ["homepage", "poster_path", "tagline", "belongs_to_collection", "adult", "video", "id", "overview", "imdb_id"]

# merge cols
drop_cols = list(set(high_missing_cols + useless_cols))

# drop
df = df.drop(columns=drop_cols)
df = df.dropna(subset=['runtime'])

df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
Index: 43645 entries, 0 to 45465
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   genres                43645 non-null  object
 1   original_language     43635 non-null  object
 2   original_title        43645 non-null  object
 3   popularity            43645 non-null  object
 4   production_companies  43645 non-null  object
 5   production_countries  43645 non-null  object
 6   release_date          43595 non-null  object
 7   runtime               43645 non-null  float64
 8   spoken_languages      43645 non-null  object
 9   status                43585 non-null  object
 10  title                 43645 non-null  object
 11  vote_average          43645 non-null  float64
 12  vote_count            43645 non-null  float64
dtypes: float64(3), object(10)
memory usage: 4.7+ MB

genres                   0
original_language       10
original_title           0
popularity               0
production_companies     0
production_countries     0
release_date            50
runtime                  0
spoken_languages         0
status                  60
title                    0
vote_average             0
vote_count               0
dtype: int64

## Data type transformation

In [5]:
# Time type
df["release_date"] = pd.to_datetime(df["release_date"], errors="coerce")
df["release_date"] = df["release_date"].dt.year

# Transform JSON to list
json_cols = ["genres", "production_companies", "production_countries", "spoken_languages"]
for j_col in json_cols:
    df[j_col] = df[j_col].apply(
        lambda x: [d['name'] for d in ast.literal_eval(x)] 
        if isinstance(x, str) else []
)

In [6]:
df.head()

,genres,original_language,original_title,popularity,production_companies,production_countries,release_date,runtime,spoken_languages,status,title,vote_average,vote_count
0,"[Animation, Comedy, Family]",en,Toy Story,21.946943,[Pixar Animation Studios],[United States of America],1995.0,81.0,[English],Released,Toy Story,7.7,5415.0
1,"[Adventure, Fantasy, Family]",en,Jumanji,17.015539,"[TriStar Pictures, Teitler Film, Interscope Co...",[United States of America],1995.0,104.0,"[English, Français]",Released,Jumanji,6.9,2413.0
2,"[Romance, Comedy]",en,Grumpier Old Men,11.7129,"[Warner Bros., Lancaster Gate]",[United States of America],1995.0,101.0,[English],Released,Grumpier Old Men,6.5,92.0
3,"[Comedy, Drama, Romance]",en,Waiting to Exhale,3.859495,[Twentieth Century Fox Film Corporation],[United States of America],1995.0,127.0,[English],Released,Waiting to Exhale,6.1,34.0
4,[Comedy],en,Father of the Bride Part II,8.387519,"[Sandollar Productions, Touchstone Pictures]",[United States of America],1995.0,106.0,[English],Released,Father of the Bride Part II,5.7,173.0

## save the clean data

In [7]:
df.to_csv("../data/processed/clean_code.csv", index=False)